.PHONY: clean All

All:
	@echo "----------Building project:[ Integers - Debug ]----------"
	@"$(MAKE)" -f  "Integers.mk"
clean:
	@echo "----------Cleaning project:[ Integers - Debug ]----------"
	@"$(MAKE)" -f  "Integers.mk" clean
