.PHONY: clean All

All:
	@echo "----------Building project:[ C_add_mul - Debug ]----------"
	@"$(MAKE)" -f  "C_add_mul.mk"
clean:
	@echo "----------Cleaning project:[ C_add_mul - Debug ]----------"
	@"$(MAKE)" -f  "C_add_mul.mk" clean
