.PHONY: clean All

All:
	@echo "----------Building project:[ Adt - Debug ]----------"
	@"$(MAKE)" -f  "Adt.mk"
clean:
	@echo "----------Cleaning project:[ Adt - Debug ]----------"
	@"$(MAKE)" -f  "Adt.mk" clean
